#ifndef SRC_AUDIO_CLIPS_H
#define SRC_AUDIO_CLIPS_H

#define SOUNDS_DOG_PANT_IDLE_1 0
#define SOUNDS_DOG_WALKING_LOOP_2 1
#define SOUNDS_DOG_JUMP_GRUNT_5 2
#define SOUNDS_DOG_BARK_1 3
#define SOUNDS_DOG_BARK_7 4
#define SOUNDS_PUNCHIMPACT 5
#define SOUNDS_DOG_ATTACK2 6
#define SOUNDS_FOOTSTEP2 7
#define SOUNDS_DOG_ATTACK1 8
#define SOUNDS_DOG_WALKING_LOOP_1 9
#define SOUNDS_DEATHSFX 10
#define SOUNDS_DOG_JUMP_GRUNT_2 11
#define SOUNDS_DOG_INJURED_GRUNT_1 12
#define SOUNDS_DOG_JUMP_GRUNT_1 13
#define SOUNDS_UI_SELECT3 14
#define SOUNDS_DOG_JUMP_GRUNT_6 15
#define SOUNDS_UI_SELECT2 16
#define SOUNDS_DOG_BARK_2 17
#define SOUNDS_FOOTSTEP1 18
#define SOUNDS_POWERUP_PICKUP 19
#define SOUNDS_DOG_ATTACK3 20
#define SOUNDS_DOG_JUMP_GRUNT_7 21
#define SOUNDS_FOOTSTEP0 22
#define SOUNDS_FOOTSTEP4 23
#define SOUNDS_FOOTSTEP3 24
#define SOUNDS_DOG_INJURED_GRUNT_2 25
#define SOUNDS_DOG_PANT_IDLE_2 26
#define SOUNDS_DOG_JUMP_GRUNT_4 27
#define SOUNDS_PUNCH 28
#define SOUNDS_DOG_BARK_3 29
#define SOUNDS_DOG_BARK_5 30
#define SOUNDS_DOG_BARK_4 31
#define SOUNDS_DOG_JUMP_GRUNT_3 32
#define SOUNDS_DOG_BARK_6 33
#define SOUNDS_FLAGCAP 34
#define SOUNDS_UI_SELECT 35
#define SOUNDS_CATMEOW1 36

#endif